apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo
spec:
  requestedFreight:
    - origin:
        kind: Stage
        name: qa
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/rajaramiotfal/kargo-argocd-demo.git
            branch: main
        - uses: kustomize-set-image
          config:
            images:
              - name: docker.io/rajarammurali513/demoapp
        - uses: git-commit
          config:
            message: "Promote to Prod"
        - uses: git-push